#include<stdio.h>
int main()
{
	long long int sum1,sum2,sum;
	while(scanf("%lld",&sum1)!=EOF)
	{
		sum=0;
		printf("Hailstone generated by %lld:\n",sum1);
		while(sum1!=1)
		{
			printf("%lld ",sum1);
			if(sum1%2==0)
			sum1/=2;
			else
			sum1=sum1*3+1;
			sum++;
		}
		printf("%ld\n",sum1);
		printf("Number of hailstone generated:%lld\n",sum+1);
		printf("\n");
	}
}
